# Generated by Django 5.0.4 on 2024-05-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('emp_id', models.CharField(max_length=200)),
                ('phone', models.IntegerField(max_length=20)),
                ('address', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=10)),
                ('working', models.BooleanField(default=True)),
            ],
        ),
    ]
